# Generated by Django 3.2.7 on 2021-10-15 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211016_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]