# Generated by Django 3.2.7 on 2021-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('is_driver', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=50)),
                ('total_socore', models.FloatField(max_length=50)),
            ],
        ),
    ]
