# Generated by Django 3.2.7 on 2021-10-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
