# Generated by Django 3.2.7 on 2021-10-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_matchdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='total_socore',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
