# Generated by Django 3.2.7 on 2021-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_request_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='client_evaluation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='driver_evaluation',
            field=models.FloatField(null=True),
        ),
    ]
