# Generated by Django 3.2.7 on 2021-10-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
