# Generated by Django 3.2.7 on 2021-10-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211006_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='messages',
        ),
        migrations.RenameModel(
            old_name='request',
            new_name='requests',
        ),
    ]
