# Generated by Django 3.2.7 on 2021-10-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_info_total_socore'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='total_number',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='total_socore',
            field=models.FloatField(max_length=50),
        ),
    ]
