# Generated by Django 3.2.7 on 2021-10-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211020_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='total_number',
            field=models.FloatField(default=1, max_length=50),
        ),
    ]
