# Generated by Django 3.2.7 on 2021-10-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_info_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='hashed_pass',
        ),
    ]
