# Generated by Django 3.2.7 on 2021-10-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211014_2227'),
        ('main', '0013_auto_20211014_2312'),
        ('main', '0013_remove_user_info_hashed_pass'),
    ]

    operations = [
    ]
